
server:
    port: 8281

    
spring:
    banner:
    charset: utf-8
    application:
             name: springboot2-elasticsearch
    http:
      encoding:
        charset: utf-8
        enabled: true
        force: true
    messages:
      encoding: UTF-8

    data:
      elasticsearch:
        repositories:
          enabled: true
        cluster-nodes: sh-r510-03-vm1:9300
        cluster-name: my-application




